In [15]:
import tensorflow as tf
import numpy as np

In [4]:
x = tf.random.normal((32, 9, 9, 9))
x = tf.nn.softmax(x, axis = -1)

In [11]:
lines = tf.reduce_sum(x, axis = 1)
rows = tf.reduce_sum(x, axis = 2)

In [31]:
# [BS, ROWS, COLUMNS , SOFTMAX PREDICTIONS FOR NUMBERS]
a = np.random.randint(1, 10, size = (32,9,9,9))

first = a[:,0:3, 0:3]
second = a[:,3:6, 0:3]
third = a[:,6:, 0:3]
forth = a[:,0:3, 3:6]

second.shape

(32, 3, 3, 9)

In [36]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [0, 3, 6],
       [0, 3, 6]], dtype=int32)>

In [37]:
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]], dtype=int32)>

In [54]:
start_slices = []
size = [-1, 3, 3, -1]

for i in range(3):
    for y in range(3):
        start_slices.append([0,i,y,0])

start_slices = tf.convert_to_tensor(start_slices)
size = tf.convert_to_tensor(size)

MSE = tf.keras.losses.MeanSquaredError()

In [60]:
@tf.function
def some(x):
    
    reg_loss = tf.convert_to_tensor(0, tf.float32)
    
    for start in start_slices:
    
        reg = tf.slice(x, start,size)
        reg = tf.reduce_sum(x, axis = [1, 2])
        reg_loss += MSE(reg, tf.ones_like(reg))
        
    return reg_loss
some(x)

<dtype: 'float32'>


<tf.Tensor: shape=(), dtype=float32, numpy=584.5774>

In [44]:
x = tf.random.normal((32, 9, 9, 9))
x = tf.nn.softmax(x, axis = -1)



<tf.Tensor: shape=(32, 3, 3, 9), dtype=float32, numpy=
array([[[[0.01750506, 0.15122369, 0.17435786, ..., 0.0417024 ,
          0.12103794, 0.13905118],
         [0.1113411 , 0.14706735, 0.04301343, ..., 0.12422746,
          0.05766663, 0.13320026],
         [0.13045608, 0.06224783, 0.12784591, ..., 0.05909099,
          0.04781274, 0.0900754 ]],

        [[0.02369948, 0.06393063, 0.12548219, ..., 0.04708081,
          0.31691903, 0.07688394],
         [0.06210508, 0.01405715, 0.09691297, ..., 0.311723  ,
          0.14497983, 0.14858662],
         [0.3867537 , 0.09702925, 0.03015258, ..., 0.09683461,
          0.2230127 , 0.03351224]],

        [[0.00622352, 0.26943585, 0.22505976, ..., 0.06751651,
          0.00988237, 0.06029557],
         [0.5058685 , 0.01642558, 0.15443641, ..., 0.14355189,
          0.00483608, 0.05423111],
         [0.1552964 , 0.01623082, 0.00750075, ..., 0.03751862,
          0.5376502 , 0.02466468]]],


       [[[0.12302526, 0.0698134 , 0.06832591, ..., 0.11

In [41]:
indices = tf.range(0, 9, 3)

# Create a 2D grid of indices
x, y = tf.meshgrid(indices, indices)

# Stack the grids and reshape to the desired shape
result = tf.stack([x, y], axis=-1)
result

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[0, 0],
        [3, 0],
        [6, 0]],

       [[0, 3],
        [3, 3],
        [6, 3]],

       [[0, 6],
        [3, 6],
        [6, 6]]], dtype=int32)>

In [26]:
tf.gather_nd(x,[8,0], batch_dims = 0)

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0.07503512, 0.0301964 , 0.04526168, 0.14543614, 0.06041303,
        0.11091594, 0.26540056, 0.20170009, 0.06564103],
       [0.05157891, 0.04501738, 0.16043185, 0.02796692, 0.05130606,
        0.18941206, 0.08477196, 0.02791451, 0.36160037],
       [0.15074544, 0.04033848, 0.08168975, 0.10358663, 0.17981604,
        0.02841026, 0.02597167, 0.13174862, 0.2576931 ],
       [0.07222874, 0.10863843, 0.33504733, 0.22243725, 0.09676608,
        0.08871946, 0.04874487, 0.01174521, 0.01567267],
       [0.08105116, 0.30621657, 0.2315626 , 0.23994154, 0.0147973 ,
        0.07642709, 0.02693532, 0.02065793, 0.00241056],
       [0.04951591, 0.04473905, 0.06921498, 0.17982097, 0.41507772,
        0.01467265, 0.07738764, 0.09077614, 0.05879492],
       [0.22201037, 0.07055154, 0.19883673, 0.0917956 , 0.05572367,
        0.00934968, 0.2202743 , 0.02797909, 0.10347912],
       [0.05456733, 0.19371325, 0.09047479, 0.13502602, 0.05345863,
        0