In [1]:
import numpy as np
from functools import reduce

In [12]:
class RowPermutation:
    def __init__(self, from_, to_):
        self.from_ = from_
        self.to_ = to_
    
    def __call__(self, matrix):
        r = np.copy(matrix)
        r[[self.to_,self.from_]] = r[[self.from_,self.to_]]
        #print("RowPermutation(", self.from_,",",self.to_,"):", r)
        return r


""" class ColumnPermutation:
    def __init__(self, from_, to_):
        self.from_ = from_
        self.to_ = to_
    
    def __call__(self, matrix):
        matrix[:,[self.to_,self.from_]] = matrix[:,[self.from_,self.to_]]
        return matrix """


class TranposePermutation:
    def __init__(self):
        pass

    def __call__(self, matrix):
        #print("TransposePermutation(", "):", matrix.T)
        return matrix.T


class MirrorPermutation:
    def __init__(self, axis):
        self.axis = axis

    def __call__(self, matrix):
        #print("RotateClockwisePermutation(", self.nturns, "):", np.rot90(matrix, k=-self.nturns))
        return np.flip(matrix, axis=self.axis)


class SwapDigitsPermutation:
    def __init__(self, dig1, dig2):
        self.dig1 = dig1
        self.dig2 = dig2
    
    def __call__(self, matrix):
        swapper = np.where(matrix==self.dig1, self.dig2, self.dig1)
        r = np.where((matrix==self.dig1) | (matrix==self.dig2), swapper, matrix)
        #print("SwapDigitsPermutation(", self.dig1,",",self.dig2,"):", r)
        return r





In [13]:
compose = lambda F: reduce(lambda f, g: lambda x: g(f(x)), F)

In [15]:
a = np.arange(16).reshape((4,4))
print(a)
perms = [
    RowPermutation(0,1),
    TranposePermutation(),
    RowPermutation(1,2),
    MirrorPermutation(1),
    SwapDigitsPermutation(4,6)
]
r = compose(perms)(a)
print(r)
print(compose(reversed(perms))(r))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12  8  0  6]
 [14 10  2  4]
 [13  9  1  5]
 [15 11  3  7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
