In [2]:
from load_data import get_data, get_tf_dataset
from deepsudoku.utils import visualize_sudoku
import tensorflow as tf
from deepsudoku.utils import visualize_sudoku
import numpy as np
import tensorflow as tf
import tensorflow as tf
import numpy as np
from metrics_and_wrapper import  SudukoWrapper
from architectures import *
from load_data import get_data, get_tf_dataset


train_df = get_data("train", "realistic_easy_data").sample(frac=1)


In [11]:
back_bone = same_transformer()
model = SudukoWrapper(back_bone)
CROSS = tf.keras.losses.SparseCategoricalCrossentropy()

model.compile("Adam", CROSS, )


In [6]:
train_df = get_data("train", "comp_our_data").sample(frac=1)
train_ds = get_tf_dataset(train_df.iloc[:1000])
train_ds = train_ds.batch(32)

In [12]:
for x,y in train_ds:
    break

In [32]:
before = model.trainable_weights[-2].numpy()
model.train_step((x,y))
after = model.trainable_weights[-2].numpy()

In [33]:
before - after

array([[ 2.92658806e-05,  2.29179859e-05, -4.99784946e-05, ...,
         7.03334808e-06,  8.10995698e-06, -2.86847353e-05],
       [ 5.53950667e-05,  9.31918621e-05, -1.25139952e-04, ...,
         2.45571136e-05,  3.06367874e-05, -9.63658094e-05],
       [-1.05705112e-04, -2.02417374e-04,  2.79605389e-04, ...,
        -1.19518489e-04,  6.41494989e-06,  2.54526734e-04],
       ...,
       [-5.21987677e-05, -3.23802233e-05,  6.00218773e-05, ...,
         9.91229899e-06, -3.24100256e-05,  2.23778188e-05],
       [ 2.27391720e-05,  3.67909670e-05, -5.67110255e-05, ...,
         3.52039933e-05, -1.49160624e-05, -6.09206036e-05],
       [ 5.45680523e-05,  8.51349905e-05, -1.41948462e-04, ...,
         4.71472740e-05, -5.51342964e-07, -1.17756426e-04]], dtype=float32)

In [20]:
pred = tf.argmax( model(x[None,:]), -1)[0]
pred

<tf.Tensor: shape=(9, 9), dtype=int64, numpy=
array([[8, 7, 8, 4, 5, 1, 0, 3, 2],
       [5, 2, 0, 6, 3, 8, 4, 7, 1],
       [3, 1, 4, 0, 2, 7, 8, 5, 8],
       [1, 4, 7, 8, 6, 2, 5, 0, 3],
       [0, 8, 3, 1, 4, 5, 2, 6, 7],
       [2, 5, 5, 3, 7, 0, 1, 6, 8],
       [8, 5, 1, 7, 0, 3, 6, 2, 4],
       [7, 0, 6, 2, 1, 3, 1, 8, 5],
       [4, 3, 2, 5, 1, 6, 7, 8, 0]])>